// Mock data for development and testing

export const MOCK_USER_HOLDINGS = [
  {
    id: '1',
    asset_id: 'real-estate-1',
    asset_name: 'Downtown Office Complex',
    asset_type: 'real_estate',
    quantity: 10,
    purchase_price: 50000,
    current_value: 52500,
    purchase_date: '2024-01-15T00:00:00Z',
    user_id: 'demo-user'
  },
  {
    id: '2',
    asset_id: 'real-estate-2',
    asset_name: 'Residential Apartments',
    asset_type: 'real_estate',
    quantity: 25,
    purchase_price: 100000,
    current_value: 105000,
    purchase_date: '2024-02-20T00:00:00Z',
    user_id: 'demo-user'
  }
];

export const MOCK_KYC_STATUS = {
  status: 'pending',
  verification_level: 'basic',
  verified_at: null,
  expires_at: null,
  documents_submitted: ['passport', 'address_proof'],
  last_updated: new Date().toISOString()
};

export const MOCK_LOANS = [
  {
    id: '1',
    user_id: 'demo-user',
    amount: 10000,
    currency: 'USD',
    interest_rate: 5.5,
    duration_days: 365,
    collateral_type: 'XLM',
    collateral_amount: 15000,
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    due_date: '2025-01-01T00:00:00Z',
    repaid_amount: 2000,
    remaining_amount: 8550
  },
  {
    id: '2',
    user_id: 'demo-user',
    amount: 5000,
    currency: 'USD',
    interest_rate: 4.5,
    duration_days: 180,
    collateral_type: 'USDC',
    collateral_amount: 7000,
    status: 'active',
    created_at: '2024-03-15T00:00:00Z',
    due_date: '2024-09-15T00:00:00Z',
    repaid_amount: 1000,
    remaining_amount: 4112.5
  }
];

export const MOCK_RWA_ASSETS = [
  {
    id: 'real-estate-1',
    asset_code: 'RE01',
    issuer_address: 'GDEMOISSUERADDRESS0000000000000000000000001',
    asset_type: 'real_estate' as const,
    name: 'Harborfront Office Suites',
    description: 'Grade-A coastal office complex with anchor tenants.',
    detailed_info: {
      location: 'San Francisco, CA',
      occupancy: '92%',
      lease_terms: '5-10 years',
    },
    image_url: '/assets/banner.svg',
    document_urls: ['https://example.com/memo.pdf'],
    unit_price: 5000,
    total_supply: 1000000,
    available_supply: 750000,
    min_investment: 2500,
    max_investment: 500000,
    yield_type: 'fixed' as const,
    annual_yield_percent: 7.2,
    yield_frequency: 'quarterly' as const,
    risk_level: 'medium' as const,
    requires_kyc: true,
    min_kyc_level: 1,
    accredited_only: false,
    status: 'active' as const,
    is_featured: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'treasury-bond-1',
    asset_code: 'TB01',
    issuer_address: 'GDEMOISSUERADDRESS0000000000000000000000002',
    asset_type: 'bond' as const,
    name: 'US 2Y Treasuries Basket',
    description: 'Tokenized exposure to short-duration US treasuries.',
    detailed_info: {
      duration: '2 years',
      coupon: '4.1%',
    },
    image_url: '/assets/banner.svg',
    document_urls: ['https://example.com/treasuries.pdf'],
    unit_price: 100,
    total_supply: 500000,
    available_supply: 420000,
    min_investment: 100,
    max_investment: null,
    yield_type: 'fixed' as const,
    annual_yield_percent: 4.1,
    yield_frequency: 'monthly' as const,
    risk_level: 'low' as const,
    requires_kyc: true,
    min_kyc_level: 0,
    accredited_only: false,
    status: 'active' as const,
    is_featured: false,
    created_at: '2024-12-01T00:00:00Z',
  },
  {
    id: 'gold-vault-1',
    asset_code: 'GLD01',
    issuer_address: 'GDEMOISSUERADDRESS0000000000000000000000003',
    asset_type: 'commodity' as const,
    name: 'Vaulted Gold Notes',
    description: 'Backed by vaulted, insured gold reserves.',
    detailed_info: {
      vault: 'Zurich',
      insurance: 'Lloyds',
    },
    image_url: '/assets/banner.svg',
    document_urls: ['https://example.com/gold.pdf'],
    unit_price: 65,
    total_supply: 100000,
    available_supply: 85000,
    min_investment: 650,
    max_investment: 20000,
    yield_type: 'none' as const,
    annual_yield_percent: 0,
    yield_frequency: 'none' as const,
    risk_level: 'medium' as const,
    requires_kyc: false,
    min_kyc_level: 0,
    accredited_only: false,
    status: 'active' as const,
    is_featured: false,
    created_at: '2024-11-10T00:00:00Z',
  },
];
